version: '3.8'

services:
  redis-node1:
    image: redis:latest
    container_name: redis-node1
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7001:6379"
    networks:
      - redis-cluster-network

  redis-node2:
    image: redis:latest
    container_name: redis-node2
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7002:6379"
    networks:
      - redis-cluster-network

  redis-node3:
    image: redis:latest
    container_name: redis-node3
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7003:6379"
    networks:
      - redis-cluster-network

networks:
  redis-cluster-network:
    driver: bridge
