version: '3.9'

services:
  redis-node-1:
    image: redis
    container_name: redis-node-1
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis-1.conf:/usr/local/etc/redis/redis.conf
    ports:
      # Redis 기본 포트 (클라이언트 연결용)
      - "7001:6379"
      # 클러스터 통신용 포트 (Redis 노드 간 통신용)
      - "17001:16379"
    networks:
      - redis-cluster

  redis-node-2:
    image: redis
    container_name: redis-node-2
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis-2.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "7002:6379"
      - "17002:16379"
    networks:
      - redis-cluster

  redis-node-3:
    image: redis
    container_name: redis-node-3
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis-3.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "7003:6379"
      - "17003:16379"
    networks:
      - redis-cluster

networks:
  redis-cluster:
    driver: bridge